import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession } from "@/lib/auth";
import { cookies } from "next/headers";
import axios from "axios";
import ClientStartup from "@/components/ClientStartup";
axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_URL;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientStartup />
      <body className={inter.className}>{children}</body>
    </html>
  );
}