// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod'
import { makeRoute } from './makeRoute'

const defaultInfo = {
    search: z.object({}),
}

import * as LoggedDashboardAvailabilitiesCalendarRoute from '@/app/(logged)dashboardavailabilitiescalendarpage.info'
import * as LoggedDashboardAvailabilitiesListRoute from '@/app/(logged)dashboardavailabilitieslistpage.info'
import * as LoggedDashboardCommentsRoute from '@/app/(logged)dashboardcommentspage.info'
import * as LoggedDashboardCommentsIdRoute from '@/app/(logged)dashboardcomments[id]page.info'
import * as LoggedDashboardCommentsIdEditRoute from '@/app/(logged)dashboardcomments[id]editpage.info'
import * as LoggedDashboardImagesRoute from '@/app/(logged)dashboardimagespage.info'
import * as LoggedDashboardImagesIdRoute from '@/app/(logged)dashboardimages[id]page.info'
import * as LoggedDashboardImagesIdEditRoute from '@/app/(logged)dashboardimages[id]editpage.info'
import * as LoggedDashboardReservationsCalendarRoute from '@/app/(logged)dashboard\reservationscalendarpage.info'
import * as LoggedDashboardReservationsListRoute from '@/app/(logged)dashboard\reservationslistpage.info'
import * as LoggedDashboardRulesRoute from '@/app/(logged)dashboard\rulespage.info'
import * as LoggedDashboardRulesIdRoute from '@/app/(logged)dashboard\rules[id]page.info'
import * as LoggedDashboardRulesIdEditRoute from '@/app/(logged)dashboard\rules[id]editpage.info'
import * as LoggedDashboardServicesRoute from '@/app/(logged)dashboardservicespage.info'
import * as LoggedDashboardServicesIdRoute from '@/app/(logged)dashboardservices[id]page.info'
import * as LoggedDashboardServicesIdEditRoute from '@/app/(logged)dashboardservices[id]editpage.info'
import * as LoggedDashboardSpasRoute from '@/app/(logged)dashboardspaspage.info'
import * as LoggedDashboardSpasIdRoute from '@/app/(logged)dashboardspas[spaId]page.info'
import * as LoggedDashboardSpasIdEditRoute from '@/app/(logged)dashboardspas[spaId]editpage.info'
import * as LoggedDashboardTagsRoute from '@/app/(logged)dashboard\tagspage.info'
import * as LoggedDashboardTagsIdRoute from '@/app/(logged)dashboard\tags[id]page.info'
import * as LoggedDashboardTagsIdEditRoute from '@/app/(logged)dashboard\tags[id]editpage.info'
import * as LoggedDashboardWebsiteFaqRoute from '@/app/(logged)dashboardwebsite\faqpage.info'
import * as LoggedDashboardWebsiteHomeRoute from '@/app/(logged)dashboardwebsitehomepage.info'
import * as LoggedDashboardWebsiteRulesRoute from '@/app/(logged)dashboardwebsite\rulespage.info'
import * as LoginRoute from '@/app/loginpage.info'

export const LoggedDashboardAvailabilitiesCalendar = makeRoute(
    '/(logged)/dashboard/availabilities/calendar',
    {
        ...defaultInfo,
        ...LoggedDashboardAvailabilitiesCalendarRoute.Route,
    }
)
export const LoggedDashboardAvailabilitiesList = makeRoute(
    '/(logged)/dashboard/availabilities/list',
    {
        ...defaultInfo,
        ...LoggedDashboardAvailabilitiesListRoute.Route,
    }
)
export const LoggedDashboardComments = makeRoute(
    '/(logged)/dashboard/comments',
    {
        ...defaultInfo,
        ...LoggedDashboardCommentsRoute.Route,
    }
)
export const LoggedDashboardCommentsId = makeRoute(
    '/(logged)/dashboard/comments/[id]',
    {
        ...defaultInfo,
        ...LoggedDashboardCommentsIdRoute.Route,
    }
)
export const LoggedDashboardCommentsIdEdit = makeRoute(
    '/(logged)/dashboard/comments/[id]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardCommentsIdEditRoute.Route,
    }
)
export const LoggedDashboardImages = makeRoute('/(logged)/dashboard/images', {
    ...defaultInfo,
    ...LoggedDashboardImagesRoute.Route,
})
export const LoggedDashboardImagesId = makeRoute(
    '/(logged)/dashboard/images/[id]',
    {
        ...defaultInfo,
        ...LoggedDashboardImagesIdRoute.Route,
    }
)
export const LoggedDashboardImagesIdEdit = makeRoute(
    '/(logged)/dashboard/images/[id]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardImagesIdEditRoute.Route,
    }
)
export const LoggedDashboardReservationsCalendar = makeRoute(
    '/(logged)/dashboard/reservations/calendar',
    {
        ...defaultInfo,
        ...LoggedDashboardReservationsCalendarRoute.Route,
    }
)
export const LoggedDashboardReservationsList = makeRoute(
    '/(logged)/dashboard/reservations/list',
    {
        ...defaultInfo,
        ...LoggedDashboardReservationsListRoute.Route,
    }
)
export const LoggedDashboardRules = makeRoute('/(logged)/dashboard/rules', {
    ...defaultInfo,
    ...LoggedDashboardRulesRoute.Route,
})
export const LoggedDashboardRulesId = makeRoute(
    '/(logged)/dashboard/rules/[id]',
    {
        ...defaultInfo,
        ...LoggedDashboardRulesIdRoute.Route,
    }
)
export const LoggedDashboardRulesIdEdit = makeRoute(
    '/(logged)/dashboard/rules/[id]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardRulesIdEditRoute.Route,
    }
)
export const LoggedDashboardServices = makeRoute(
    '/(logged)/dashboard/services',
    {
        ...defaultInfo,
        ...LoggedDashboardServicesRoute.Route,
    }
)
export const LoggedDashboardServicesId = makeRoute(
    '/(logged)/dashboard/services/[id]',
    {
        ...defaultInfo,
        ...LoggedDashboardServicesIdRoute.Route,
    }
)
export const LoggedDashboardServicesIdEdit = makeRoute(
    '/(logged)/dashboard/services/[id]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardServicesIdEditRoute.Route,
    }
)
export const LoggedDashboardSpas = makeRoute('/(logged)/dashboard/spas', {
    ...defaultInfo,
    ...LoggedDashboardSpasRoute.Route,
})
export const LoggedDashboardSpasId = makeRoute(
    '/(logged)/dashboard/spas/[spaId]',
    {
        ...defaultInfo,
        ...LoggedDashboardSpasIdRoute.Route,
    }
)
export const LoggedDashboardSpasIdEdit = makeRoute(
    '/(logged)/dashboard/spas/[spaId]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardSpasIdEditRoute.Route,
    }
)
export const LoggedDashboardTags = makeRoute('/(logged)/dashboard/tags', {
    ...defaultInfo,
    ...LoggedDashboardTagsRoute.Route,
})
export const LoggedDashboardTagsId = makeRoute(
    '/(logged)/dashboard/tags/[id]',
    {
        ...defaultInfo,
        ...LoggedDashboardTagsIdRoute.Route,
    }
)
export const LoggedDashboardTagsIdEdit = makeRoute(
    '/(logged)/dashboard/tags/[id]/edit',
    {
        ...defaultInfo,
        ...LoggedDashboardTagsIdEditRoute.Route,
    }
)
export const LoggedDashboardWebsiteFaq = makeRoute(
    '/(logged)/dashboard/website/faq',
    {
        ...defaultInfo,
        ...LoggedDashboardWebsiteFaqRoute.Route,
    }
)
export const LoggedDashboardWebsiteHome = makeRoute(
    '/(logged)/dashboard/website/home',
    {
        ...defaultInfo,
        ...LoggedDashboardWebsiteHomeRoute.Route,
    }
)
export const LoggedDashboardWebsiteRules = makeRoute(
    '/(logged)/dashboard/website/rules',
    {
        ...defaultInfo,
        ...LoggedDashboardWebsiteRulesRoute.Route,
    }
)
export const Login = makeRoute('/login', {
    ...defaultInfo,
    ...LoginRoute.Route,
})
