"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QY8B3xEtSBG
 */
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useState } from "react"

type ContactFormProps = {
  onSubmit: (data: FormData) => Promise<{state: true} | {state: false, message: string}>
}

export default function ContactForm({ onSubmit }: ContactFormProps) {
  const [error, setError] = useState<string | undefined>()
  const [success, setSuccess] = useState<true | undefined>()
  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    onSubmit(new FormData(event.currentTarget)).then((response) => {
      console.log(response)
      if(!response.state) {
        setError(response.message)
      }else {
        setSuccess(true)
      }
    })
  }
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
        <div>
          <h2 className="text-2xl font-semibold mb-4">Des questions ? Merci de remplir le formulaire ci-dessous.</h2>
          <form className="space-y-6" onSubmit={handleSubmit}>
            <div>
              <label className="block text-sm font-medium mb-1" htmlFor="name">
                Votre nom (obligatoire)
              </label>
              <Input name="name" id="name" placeholder="Jean Dupont" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1" htmlFor="email">
                Votre adresse de messagerie (obligatoire)
              </label>
              <Input name="email" id="email" placeholder="jean.dupont@example.com" type="email" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1" htmlFor="subject">
                Objet
              </label>
              <Input name="subject" id="subject" placeholder="Sujet de votre message" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1" htmlFor="message">
                Votre message
              </label>
              <Textarea name="message" className="h-32" id="message" placeholder="Tapez votre message ici." />
            </div>
            {success && <p className="text-green-500 mt-4">your question has been transmited</p>}
            {error && <p className="text-red-500 mt-4">{error}</p>}
            <Button>Envoyer</Button>
          </form>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">Avant de nous contacter</h2>
          <p>La réponse à votre question peut être dans la section FAQ ci-dessous.</p>
          <p className="mt-2">Veuillez consulter notre section FAQ ci-dessous.</p>
        </div>
      </div>
    </div>
  )
}
