'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QY8B3xEtSBG
 */
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import { useState } from 'react'

type ContactFormProps = {
    onSubmit: (
        data: FormData
    ) => Promise<{ state: true } | { state: false; message: string }>
}

export default function ContactForm({ onSubmit }: ContactFormProps) {
    const [error, setError] = useState<string | undefined>()
    const [success, setSuccess] = useState<true | undefined>()
    function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault()
        onSubmit(new FormData(event.currentTarget)).then((response) => {
            if (!response.state) {
                setError(response.message)
            } else {
                setSuccess(true)
            }
        })
    }
    return (
        <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-16 md:grid-cols-2">
                <div>
                    <h2 className="mb-4 text-2xl font-semibold">
                        Des questions ? Merci de remplir le formulaire
                        ci-dessous.
                    </h2>
                    <form className="space-y-6" onSubmit={handleSubmit}>
                        <div>
                            <label
                                className="mb-1 block text-sm font-medium"
                                htmlFor="name"
                            >
                                Votre nom (obligatoire)
                            </label>
                            <Input
                                name="name"
                                id="name"
                                placeholder="Jean Dupont"
                                className="placeholder:text-white"
                            />
                        </div>
                        <div>
                            <label
                                className="mb-1 block text-sm font-medium"
                                htmlFor="email"
                            >
                                Votre adresse de messagerie (obligatoire)
                            </label>
                            <Input
                                name="email"
                                id="email"
                                placeholder="jean.dupont@example.com"
                                type="email"
                                className="placeholder:text-white"
                            />
                        </div>
                        <div>
                            <label
                                className="mb-1 block text-sm font-medium"
                                htmlFor="subject"
                            >
                                Objet
                            </label>
                            <Input
                                name="subject"
                                id="subject"
                                placeholder="Sujet de votre message"
                                className="placeholder:text-white"
                            />
                        </div>
                        <div>
                            <label
                                className="mb-1 block text-sm font-medium"
                                htmlFor="message"
                            >
                                Votre message
                            </label>
                            <Textarea
                                name="message"
                                className="h-32 placeholder:text-white"
                                id="message"
                                placeholder="Tapez votre message ici."
                            />
                        </div>
                        {success && (
                            <p className="mt-4 text-green-500">
                                your question has been transmited
                            </p>
                        )}
                        {error && <p className="mt-4 text-red-500">{error}</p>}
                        <Button>Envoyer</Button>
                    </form>
                </div>
                <div>
                    <h2 className="mb-4 text-2xl font-semibold">
                        Avant de nous contacter
                    </h2>
                    <p>
                        La réponse à votre question peut être dans la section
                        FAQ ci-dessous.
                    </p>
                    <p className="mt-2">
                        Veuillez consulter notre section FAQ ci-dessous.
                    </p>
                </div>
            </div>
        </div>
    )
}
