/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HIEHGIYdocL
 */

import Link from "next/link";

export default function footer() {
    return (
        <footer className="bg-[#8C6750] py-10 text-white">
            <div className="max-w-6xl mx-auto px-6 flex justify-between">
                <div>
                    <h5 className="font-bold uppercase mb-6">Contact</h5>
                    <ul className="space-y-4">
                        <li className="flex items-center space-x-2">
                            <LocateIcon className="text-red-600" />
                            <span>La Falaise (40mn de paris)</span>
                        </li>
                        <li className="flex items-center space-x-2">
                            <MailIcon className="text-red-600" />
                            <Link href="/contact">
                                <span>nous contacter</span>
                            </Link>
                        </li>
                        <li className="flex items-center space-x-2">
                            <InstagramIcon className="text-red-600" />
                            <span>Instagram</span>
                        </li>
                        <li className="flex items-center space-x-2">
                            <InstagramIcon className="text-red-600" />
                            <span>Tiktok</span>
                        </li>
                        <li className="flex items-center space-x-2">
                            <FacebookIcon className="text-red-600" />
                            <span>Facebook</span>
                        </li>
                    </ul>
                </div>
                <div>
                    <h5 className="font-bold uppercase mb-6">Navigation</h5>
                    <ul className="space-y-4">
                        <li>
                            <Link className="hover:underline" href="/">Accueil</Link>
                        </li>
                        <li>
                            <Link className="hover:underline" href="/reservation">Réservations</Link>
                        </li>
                        <li>
                            <Link className="hover:underline" href="/contact">Contact</Link>
                        </li>
                        <li>
                            <Link className="hover:underline" href="/faq">FAQ</Link>
                        </li>
                        <li>
                            <Link className="hover:underline" href="/reglement">Règlement de la maison</Link>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>
    );
}

function LocateIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="2" x2="5" y1="12" y2="12" />
            <line x1="19" x2="22" y1="12" y2="12" />
            <line x1="12" x2="12" y1="2" y2="5" />
            <line x1="12" x2="12" y1="19" y2="22" />
            <circle cx="12" cy="12" r="7" />
        </svg>
    );
}

function MailIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <rect width="20" height="16" x="2" y="4" rx="2" />
            <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
        </svg>
    );
}

function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
            <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
            <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
        </svg>
    );
}

function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
        </svg>
    );
}
