/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HIEHGIYdocL
 */

import Link from "next/link";
import { Links } from "./Navbar";

export default function footer() {
    return (
        <footer className="py-10 text-white">
            <div className="max-w-6xl mx-auto px-6 flex justify-between">
                <div>
                    <h5 className="font-bold uppercase mb-6">Contact</h5>
                    <ul className="space-y-4">
                        <li className="flex items-center space-x-2">
                            <MailIcon className="text-red-600" />
                            <Link href="/contact">
                                <span>nous contacter</span>
                            </Link>
                        </li>
                        <li className="flex items-center space-x-2">
                            <InstagramIcon className="text-red-600" />
                            <Link href="https://www.instagram.com/lescalesuiteandspa/">
                                <span>Instagram</span>
                            </Link>
                        </li>
                        <li className="flex items-center space-x-2">
                            <TiktokIcon className="text-red-600" />
                            <Link href="https://www.tiktok.com/@lescale.suite.spa?_t=8jvZmLXtqjo&_r=1">
                                <span>Tiktok</span>
                            </Link>
                        </li>
                        <li className="flex items-center space-x-2">
                            <SnapchatIcon className="text-red-600" />
                            <Link href="https://www.facebook.com/lescalesuiteandspa">
                                <span>Snapchat</span>
                            </Link>
                        </li>
                    </ul>
                </div>
                <div>
                    <h5 className="font-bold uppercase mb-6">Navigation</h5>
                    <ul className="space-y-4 flex flex-col">
                        <Links />
                    </ul>
                </div>
            </div>
        </footer>
    );
}

function LocateIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="2" x2="5" y1="12" y2="12" />
            <line x1="19" x2="22" y1="12" y2="12" />
            <line x1="12" x2="12" y1="2" y2="5" />
            <line x1="12" x2="12" y1="19" y2="22" />
            <circle cx="12" cy="12" r="7" />
        </svg>
    );
}

function MailIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <rect width="20" height="16" x="2" y="4" rx="2" />
            <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
        </svg>
    );
}

function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
            <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
            <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
        </svg>
    );
}

function TiktokIcon (props: React.SVGProps<SVGSVGElement>) {
    return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M448 209.9a210.1 210.1 0 0 1 -122.8-39.3V349.4A162.6 162.6 0 1 1 185 188.3V278.2a74.6 74.6 0 1 0 52.2 71.2V0l88 0a121.2 121.2 0 0 0 1.9 22.2h0A122.2 122.2 0 0 0 381 102.4a121.4 121.4 0 0 0 67 20.1z"/></svg>
}

function SnapchatIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1.5 15.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5zm5-5.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm-5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm-5-5.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-1.12 1.5-1.5 1.5z" />
        </svg>
    );
}
