/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xtw5WWaCD1O
 */

type ListProps = {
  items: string[]
}

export function List({ items }: ListProps) {
    return (
        <div className="mx-auto p-6">
            <ul className="list-none pl-5 space-y-2">
                {items.map((item, key) => <li key={key}>- {item}</li>)}
            </ul>
        </div>
    );
}
