import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/lib/fontAwesome"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} text-slate-50 min-h-screen flex flex-col justify-between`}
                style={{
                    fontFamily: '"Josefin Sans", Sans-serif'
                }}
            >
                <div className="flex grow flex-col">
                    <Navbar />
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
