import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/lib/fontAwesome";
import axios from "axios";
import { Toaster } from "@/components/ui/toaster";
import ClientStartup from "@/components/ClientStartup";
import { inter } from "@/fonts/index";
import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_URL;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${inter.className} bg-[#2e2227] text-white min-h-screen flex flex-col justify-between`}
        style={{
          fontFamily: '"Josefin Sans", Sans-serif',
        }}
      >
        <ClientStartup />
        <div className="flex grow flex-col">
          <Navbar />
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
